import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:intl/intl.dart';

class DailyPunchesDialog extends StatefulWidget {
  final Map<String, dynamic> userData;

  const DailyPunchesDialog({super.key, required this.userData});

  @override
  State<DailyPunchesDialog> createState() => _DailyPunchesDialogState();
}

class _DailyPunchesDialogState extends State<DailyPunchesDialog> {
  List<dynamic> _punches = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _fetchDailyPunches();
  }

  Future<void> _fetchDailyPunches() async {
    try {
      final response = await http.get(
        Uri.parse(
          'http://10.0.2.2:3000/api/attendance/daily-punches/${widget.userData['id']}',
        ),
      );
      if (response.statusCode == 200) {
        if (mounted) {
          setState(() {
            _punches = jsonDecode(response.body);
            _isLoading = false;
          });
        }
      } else {
        throw Exception('Failed to load data');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.all(16),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Container(
        width: double.infinity,
        height: MediaQuery.of(context).size.height * 0.85,
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Daily Punches',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF188984),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () => Navigator.of(context).pop(),
                ),
              ],
            ),
            const Divider(),
            Expanded(
              child:
                  _isLoading
                      ? const Center(
                        child: CircularProgressIndicator(
                          color: Color(0xFF188984),
                        ),
                      )
                      : _punches.isEmpty
                      ? const Center(
                        child: Text(
                          'No punch records found.',
                          style: TextStyle(fontSize: 16),
                        ),
                      )
                      : ListView.builder(
                        itemCount: _punches.length,
                        itemBuilder: (context, index) {
                          final punch = _punches[index];
                          final DateTime dateObj = DateTime.parse(
                            punch['date'],
                          );
                          final formattedDate = DateFormat(
                            'yyyy-MM-dd',
                          ).format(dateObj);

                          // Extract arrays generated by PostgreSQL array_agg
                          List<dynamic> punchIns = [];
                          List<dynamic> punchOuts = [];
                          if (punch['punch_in_times'] != null) {
                            punchIns =
                                List<dynamic>.from(
                                  punch['punch_in_times'],
                                ).where((e) => e != null).toList();
                          }
                          if (punch['punch_out_times'] != null) {
                            punchOuts =
                                List<dynamic>.from(
                                  punch['punch_out_times'],
                                ).where((e) => e != null).toList();
                          }

                          return Card(
                            margin: const EdgeInsets.only(bottom: 12),
                            elevation: 2,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Padding(
                              padding: const EdgeInsets.all(16),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    children: [
                                      const Icon(
                                        Icons.event,
                                        color: Color(0xFF188984),
                                        size: 20,
                                      ),
                                      const SizedBox(width: 8),
                                      Text(
                                        formattedDate,
                                        style: const TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black87,
                                        ),
                                      ),
                                    ],
                                  ),
                                  const SizedBox(height: 12),
                                  Row(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            const Text(
                                              "Punch Ins:",
                                              style: TextStyle(
                                                fontWeight: FontWeight.w600,
                                                color: Colors.green,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            ...punchIns.map(
                                              (t) => Padding(
                                                padding: const EdgeInsets.only(
                                                  bottom: 2,
                                                ),
                                                child: Text(
                                                  "• $t",
                                                  style: const TextStyle(
                                                    fontSize: 14,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            if (punchIns.isEmpty)
                                              const Text(
                                                "• None",
                                                style: TextStyle(
                                                  fontSize: 14,
                                                  color: Colors.grey,
                                                ),
                                              ),
                                          ],
                                        ),
                                      ),
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            const Text(
                                              "Punch Outs:",
                                              style: TextStyle(
                                                fontWeight: FontWeight.w600,
                                                color: Colors.orange,
                                              ),
                                            ),
                                            const SizedBox(height: 4),
                                            ...punchOuts.map(
                                              (t) => Padding(
                                                padding: const EdgeInsets.only(
                                                  bottom: 2,
                                                ),
                                                child: Text(
                                                  "• $t",
                                                  style: const TextStyle(
                                                    fontSize: 14,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            if (punchOuts.isEmpty)
                                              const Text(
                                                "• None",
                                                style: TextStyle(
                                                  fontSize: 14,
                                                  color: Colors.grey,
                                                ),
                                              ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                          );
                        },
                      ),
            ),
          ],
        ),
      ),
    );
  }
}
